{
    'name': "Quality Control Base - 18.0.1.0",
    'summary': """Quality Base""",
    'description': """Quality Base""",
    'module_type':'official',    
    'author': "Prixgen Tech Solutions Pvt. Ltd.",
    'company': 'Prixgen Tech Solutions Pvt. Ltd.',
    'website': 'https://www.prixgen.com',
    'App origin':"Base",    
    'category': 'Quality',
    'version': '18.0.0.1',    
    'depends': ['base',
                'purchase',
                'stock',
                'product',
                'quality',
                'quality_control',
                'mrp',
                'quality_mrp',
                'product_expiry',
                'quality_mrp_workorder',
                'hr'],
    'data': [
        'security/ir.model.access.csv',
        'security/quality_access.xml',
        'views/views.xml',
    ],
}
