{
    'name': 'Px Weighment 18.0.0.9',
    'version': '18.0.0.0',
    'author': "Prixgen Tech Solutions Pvt. Ltd.",
    'website': 'https://www.prixgen.com',
    'category': 'Weighment',
    'summary': 'Weighment',
    'origin':'Project',
    'description': """ """,
    'depends': ['stock','product','purchase','maintenance','mrp','fleet','sale_management','gate_management','sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/weighment_main_form.xml',
        'views/weighment_type_form.xml',
        
        'data/ir_sequence_data.xml',
        'views/equipments.xml',
        'views/mrp_production.xml',
        'views/stock_picking_type.xml',
        'views/product_tolerance.xml',
        'views/purchase_order.xml',
        'views/sale_order.xml',
        'views/stock_picking.xml',
        # 'report/report.xml',
        # 'report/weighment_report.xml',
    ],
    'installable': True,
    'auto_install': False,
}
