from . import account_move
from . import crm_lead
from . import inventory_config
from . import material_request
from . import product_template
from . import purchase_order
from . import sale_order
from . import purchase_request
from . import res_partner
from . import stock_move_validataion
from . import base_inherit
from . import custom_fields
from . import res_company
